### ISSUE TITLE
React & Redux group project: set up your Kanban board

### ISSUE THREAD

**Issue by Meri-MG** [Meri-MG/react-group-project#64]

**Comment by TedLivist** [comment]
## STATUS: APPROVED ✔️ ✔️

Hi @Meri-MG and @zemola,

Your board is well set up and your cards are assigned and complete, therefore your project is complete! :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in this issue if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
